### PR TITLE
Show encounter type in notification

### PR DESCRIPTION
**Pull request by alexcheveau**
Take a look when you got the time.
This is my first commit, so if I did something wrong just tell me :)

image

### CODE REVIEW

**Comment by alucas** [comment]
It's an interesting feature, but the notification title is now too large. So we need to fix that.

**Comment by mhetralla** [comment]
Maybe using a symbol or an emoji instead? Or that would be too cryptic? We can mark the Disk (Lured stop) encounters with 🔵, Incense with 🌀 and leave without mark the natural encounters, or using a 🌲.  
It seems as is he modified a lot of code to add this, is a cleaner way to do this?

**Comment by alucas** [comment]
He modified too much code, that why I didn't merge that PR yet. But the part that display the origine seem good, it just need to be displayed differently.

**Comment by alexcheveau** [comment]
Haha sorry for that ;)
What I did is just a cleaner way to pass params to mEncounterNotification.show
Instead of passing 300 values, you pass only the Pokemon Class
And for the title, agreed, using an emoji is a much better solution than showing "Wild" or "Incense"

**Comment by alucas** [comment]
I picked-up your code in the master branch, I will close that PR

**Pull request closed without merging**
